server:
  port: 8001

mybatis:
  type-aliases-package: com.cloud.springcloud.pojo
  config-location:  classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://weichenhao.cn:3310/DB01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

#Eureka的配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8001  #修改eureka上默认描述信息

#info配置
info:
  app.name: wch-springcloud
  company.name: blog.wchstudy.com